services:
  - type: web
    name: go-proxy-bingai
    oregon: Singapore
    plan: free
    env: go
    buildCommand: go build -ldflags="-s -w" -tags netgo -trimpath -o go-proxy-bingai main.go
    startCommand: ./go-proxy-bingai
    routes:
      - type: redirect
        source: /
        destination: /web/index.html
      - type: redirect
        source: /web
        destination: /web/index.html