services:
  - type: web
    name: go-proxy-bingai
    #oregon: Singapore
    plan: free
    runtime: go
    buildCommand: go build -ldflags="-s -w" -tags netgo -trimpath -o app
    startCommand: ./app
    buildFilter:
      paths:
      - frontend/**/*.js
      - ./**/*.go
      ignoredPaths:
      - api/**/*_test.go